all:
	asciidoctor -r asciidoctor-diagram -b html5 -a toc=left -a numbered -a icons=font -a source-highlighter=rouge -o database.html database.adoc


design:
	asciidoctor -r asciidoctor-diagram -b html5 -a toc=left -a numbered -a icons=font -a source-highlighter=rouge -o design.html design.adoc