// ... existing code ...
            <p className="text-white/40 text-sm font-medium">
                Feature:&nbsp;&nbsp;
                <input
                    type="radio"
                    value="option1"
                    checked
                    name="feature"
                />
                &nbsp;&nbsp;
                None
                &nbsp;&nbsp;
                <input
                    type="radio"
                    value="option2"
                    name="feature"
                />
                &nbsp;&nbsp;
                Story
                &nbsp;&nbsp;
                <input
                    type="radio"
                    value="option3"
                    name="feature"
                />
                &nbsp;&nbsp;
                Dialog
                &nbsp;&nbsp;
                <input
                    type="radio"
                    value="option4"
                    name="feature"
                />
                &nbsp;&nbsp;
                English
                &nbsp;&nbsp;
            </p>
        </div>
// ... existing code ...